server.port=9000
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_db
spring.datasource.username=postgres
spring.datasource.password=techgirl7
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=bank
spring.sql.init.mode=always
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
